### PR TITLE
"idSoundCache: error unloading data from OpenAL hardware buffer" error fix

### PR DESCRIPTION
**Pull request by bibendovsky**

### CODE REVIEW

**Comment by bibendovsky** [comment]
The patcher test build:
[eaxefx_app_patcher-v1.0.3-wip-dff7f396b27bf5f6f2b5ee248a1e3cb48239ddd6.zip](https://github.com/bibendovsky/eaxefx/files/9277458/eaxefx_app_patcher-v1.0.3-wip-dff7f396b27bf5f6f2b5ee248a1e3cb48239ddd6.zip)

**Comment by Kappa971** [comment]
Unfortunately it isn't working. If it isn't possible to implement the fix in the patcher, I have nothing against using your source port (I don't use dhewm3 just because it doesn't have EAX hardware support, instead your port is vanilla Doom 3 with the necessary fixes).

**Comment by bibendovsky** [comment]
> Unfortunately it isn't working.

It crashes or outputs the error message in the console?

**Comment by Kappa971** [comment]
> It crashes or outputs the error message in the console?

Yes, It displays the same OpenAL error in the console:
Doom 3 Screenshot 2022 08 08 - 14 47 59 01

**Comment by bibendovsky** [comment]
> Yes, It displays the same OpenAL error in the console:

Fixed:
[eaxefx_app_patcher-v1.0.3-wip-6202eb559e78bbe7c81e6329653b6bd1f79a43ae.zip](https://github.com/bibendovsky/eaxefx/files/9293751/eaxefx_app_patcher-v1.0.3-wip-6202eb559e78bbe7c81e6329653b6bd1f79a43ae.zip)

Tested with OpenAL Soft 1.22.2.
HostOAL does not have the issue in my case.

**Comment by Kappa971** [comment]
> Fixed: [eaxefx_app_patcher-v1.0.3-wip-6202eb559e78bbe7c81e6329653b6bd1f79a43ae.zip](https://github.com/bibendovsky/eaxefx/files/9293751/eaxefx_app_patcher-v1.0.3-wip-6202eb559e78bbe7c81e6329653b6bd1f79a43ae.zip)
> 
> Tested with OpenAL Soft 1.22.2. HostOAL does not have the issue in my case.

I confirm that it works now, thanks @bibendovsky.

**Pull request merged**
