### PR TITLE
Fix getting active FX slots for source

### PR DESCRIPTION
**Pull request by bibendovsky**
See #8 for details.

### CODE REVIEW

**Comment by mirh** [comment]
I'm not really sure you should put such note here, given we don't really know the original behaviour.

**Comment by bibendovsky** [comment]
> I'm not really sure you should put such note here, given we don't really know the original behaviour.

With patched version you don't hear any EAX effects (reverb, etc.) using the wrapper.
Why I *should not* to warn the user about such problem?

**Comment by bibendovsky** [comment]
Or you think it was intended "feature"?

**Comment by mirh** [comment]
Mhh no, I'm just saying that we aren't sure if missing effects is ***really*** due to a bug in your wrapper, or because of a bug in the game itself. 
There are reports of people spinning around in [circles](https://forums.beyondunreal.com/threads/ut2004-x-fi-patch-ingame-battle-sounds-missing-or-skipping.203675/) even with the original cards (and [others](https://web.archive.org/web/20110823222007/http://connect.creativelabs.com/alchemy/Lists/Games/DispForm.aspx?ID=128) reporting no issues). 

https://www.oldunreal.com/cgi-bin/yabb2/YaBB.pl?num=1399614690/135
https://web.archive.org/web/20170720035149/http://forums.creative.com/showthread.php?t=726283
@LAGonauta maybe can help

**Pull request merged**
